package com.mycompany.odevyilsonu;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hastr
 */
public class o1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(o1.class.getName());
    //kelimeleri atama kısmı
    List<String> stringList; 
    String secilenKelime;
    javax.swing.JLabel[] harfEtiketleri;
    
    String sifre;
    Random rnd = new Random();
    boolean bildiMi = false;
    
    int kelimeIndex;
    int tahminSayisi = 1;
    int gecenSureSaniye = 0;
    javax.swing.JLabel daragaciResimEtiketi = new javax.swing.JLabel();
    javax.swing.Timer oyunTimer;
    
    //Tablo 1 oyun tablosu
    String[] sutunlarOyun = {"Oyun Durumu", "Geçen Süre (Sn)"};
    DefaultTableModel model1 = new DefaultTableModel(sutunlarOyun, 0);
    
    //Tablo 2 log tablosu
    String[] sutunlarLog = {"Zaman", "GirilenDeger", "Durum"};
    DefaultTableModel model2 = new DefaultTableModel(sutunlarLog, 0);

    public o1() {
        initComponents();
        degerAtamalari();

        java.awt.CardLayout cl = new java.awt.CardLayout();
        this.getContentPane().setLayout(cl);

        this.getContentPane().add(sifreKytPanel, "KAYIT");
        this.getContentPane().add(sifreGrsPanel, "GIRIS");
        this.getContentPane().add(anaPanel, "ANAPANEL");

        setOyunButonlariAktif(false);
        
        dosyaOku();

        if (sifre != null && !sifre.trim().isEmpty()) {
            cl.show(this.getContentPane(), "GIRIS");
        } else {
            cl.show(this.getContentPane(), "KAYIT");
        }

        this.setSize(450, 300);
        this.setLocationRelativeTo(null);
        this.revalidate();
        this.repaint();
    }

    private void dosyaOku() {
        //Kelimeleri oku
        try {
            String dosyaAdi = "C:\\P2Oyun\\TXTDosyalar\\kelimeler.txt";
            Path filePath = new File(dosyaAdi).toPath();
            stringList = Files.readAllLines(filePath, Charset.defaultCharset());
        } catch (IOException iOException) {
            System.out.println("Kelimeler dosyası okunamadı: " + iOException.getMessage());
        }
        //Şifreyi oku
        try {
            String dosyaAdi = "C:\\P2Oyun\\TXTDosyalar\\sifre.txt";
            Path filePath = new File(dosyaAdi).toPath();
            sifre = Files.readString(filePath, Charset.defaultCharset());
        } catch (IOException iOException) {
            System.out.println("Dosya okunamadı ya da boş");
            sifre = "";
        }
    }

    private void degerAtamalari() {
        skorTablosu.setModel(model1);
        logTablosu.setModel(model2);
        jMenuBar1.setVisible(false);
        sifreBar.setMaximum(3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        anaPanel = new javax.swing.JPanel();
        tabPanel = new javax.swing.JTabbedPane();
        oyunTab = new javax.swing.JPanel();
        kelimePanel = new javax.swing.JPanel();
        tahminHarf = new javax.swing.JTextField();
        tahminKelimetxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnHarfTahmin = new javax.swing.JButton();
        btnKelimeTahmin = new javax.swing.JButton();
        pnlDaragaci = new javax.swing.JPanel();
        lblSure = new javax.swing.JLabel();
        skorTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        skorTablosu = new javax.swing.JTable();
        btnTemizleOyun = new javax.swing.JButton();
        logTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        logTablosu = new javax.swing.JTable();
        btnTemizleLog = new javax.swing.JButton();
        sifreGrsPanel = new javax.swing.JPanel();
        girisTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sifreBar = new javax.swing.JProgressBar();
        btnGiris = new javax.swing.JButton();
        sifreKytPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        kaydetTxtField = new javax.swing.JTextField();
        btnSifreKaydet = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        oyunBaslat = new javax.swing.JMenuItem();
        oyunSifirla = new javax.swing.JMenuItem();
        oyunDurdur = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        anaPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 51), new java.awt.Color(255, 153, 0), new java.awt.Color(255, 153, 51)));

        tabPanel.addChangeListener(this::tabPanelStateChanged);

        kelimePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout kelimePanelLayout = new javax.swing.GroupLayout(kelimePanel);
        kelimePanel.setLayout(kelimePanelLayout);
        kelimePanelLayout.setHorizontalGroup(
            kelimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 573, Short.MAX_VALUE)
        );
        kelimePanelLayout.setVerticalGroup(
            kelimePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        jLabel3.setText("Harf Tahmini:");

        jLabel4.setText("Kelime Tahmini:");

        btnHarfTahmin.setText("Tahmin");
        btnHarfTahmin.addActionListener(this::btnHarfTahminActionPerformed);

        btnKelimeTahmin.setText("Tahmin");
        btnKelimeTahmin.addActionListener(this::btnKelimeTahminActionPerformed);

        pnlDaragaci.setPreferredSize(new java.awt.Dimension(100, 228));

        javax.swing.GroupLayout pnlDaragaciLayout = new javax.swing.GroupLayout(pnlDaragaci);
        pnlDaragaci.setLayout(pnlDaragaciLayout);
        pnlDaragaciLayout.setHorizontalGroup(
            pnlDaragaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlDaragaciLayout.setVerticalGroup(
            pnlDaragaciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );

        lblSure.setText("jLabel5");

        javax.swing.GroupLayout oyunTabLayout = new javax.swing.GroupLayout(oyunTab);
        oyunTab.setLayout(oyunTabLayout);
        oyunTabLayout.setHorizontalGroup(
            oyunTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oyunTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(oyunTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(oyunTabLayout.createSequentialGroup()
                        .addGroup(oyunTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(oyunTabLayout.createSequentialGroup()
                                .addComponent(tahminKelimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnKelimeTahmin))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(oyunTabLayout.createSequentialGroup()
                                .addComponent(tahminHarf, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHarfTahmin))
                            .addComponent(lblSure, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pnlDaragaci, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        oyunTabLayout.setVerticalGroup(
            oyunTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oyunTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kelimePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(oyunTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(oyunTabLayout.createSequentialGroup()
                        .addGroup(oyunTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tahminHarf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHarfTahmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(oyunTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tahminKelimetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKelimeTahmin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSure, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlDaragaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPanel.addTab("Oyun", oyunTab);

        skorTab.setMinimumSize(new java.awt.Dimension(100, 100));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        skorTab.setLayout(flowLayout1);

        skorTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(skorTablosu);

        skorTab.add(jScrollPane1);

        btnTemizleOyun.setText("Temizle");
        btnTemizleOyun.addActionListener(this::btnTemizleOyunActionPerformed);
        skorTab.add(btnTemizleOyun);

        tabPanel.addTab("Skor Tablosu", skorTab);

        logTablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(logTablosu);

        btnTemizleLog.setText("Temizle");
        btnTemizleLog.addActionListener(this::btnTemizleLogActionPerformed);

        javax.swing.GroupLayout logTabLayout = new javax.swing.GroupLayout(logTab);
        logTab.setLayout(logTabLayout);
        logTabLayout.setHorizontalGroup(
            logTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTemizleLog)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        logTabLayout.setVerticalGroup(
            logTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(logTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTemizleLog)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabPanel.addTab("Geçmiş Log Kayıtları", logTab);

        javax.swing.GroupLayout anaPanelLayout = new javax.swing.GroupLayout(anaPanel);
        anaPanel.setLayout(anaPanelLayout);
        anaPanelLayout.setHorizontalGroup(
            anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        anaPanelLayout.setVerticalGroup(
            anaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jLabel2.setText("Şifreyi Girin -->");

        btnGiris.setText("Giriş");
        btnGiris.addActionListener(this::btnGirisActionPerformed);

        javax.swing.GroupLayout sifreGrsPanelLayout = new javax.swing.GroupLayout(sifreGrsPanel);
        sifreGrsPanel.setLayout(sifreGrsPanelLayout);
        sifreGrsPanelLayout.setHorizontalGroup(
            sifreGrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifreGrsPanelLayout.createSequentialGroup()
                .addGroup(sifreGrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sifreGrsPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(girisTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sifreGrsPanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(sifreBar, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sifreGrsPanelLayout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btnGiris)))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        sifreGrsPanelLayout.setVerticalGroup(
            sifreGrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifreGrsPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(sifreGrsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(girisTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGiris)
                .addGap(20, 20, 20)
                .addComponent(sifreBar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jLabel1.setText("Oluşturulacak Şifre :");

        btnSifreKaydet.setText("Şifreyi Kaydet");
        btnSifreKaydet.addActionListener(this::btnSifreKaydetActionPerformed);

        javax.swing.GroupLayout sifreKytPanelLayout = new javax.swing.GroupLayout(sifreKytPanel);
        sifreKytPanel.setLayout(sifreKytPanelLayout);
        sifreKytPanelLayout.setHorizontalGroup(
            sifreKytPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifreKytPanelLayout.createSequentialGroup()
                .addGroup(sifreKytPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sifreKytPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kaydetTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sifreKytPanelLayout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnSifreKaydet, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        sifreKytPanelLayout.setVerticalGroup(
            sifreKytPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sifreKytPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(sifreKytPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kaydetTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSifreKaydet)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jMenu3.setText("Ayarlar");

        oyunBaslat.setText("Oyunu Başlat");
        oyunBaslat.addActionListener(this::oyunBaslatActionPerformed);
        jMenu3.add(oyunBaslat);

        oyunSifirla.setText("Oyunu Yeniden Başlat");
        oyunSifirla.addActionListener(this::oyunSifirlaActionPerformed);
        jMenu3.add(oyunSifirla);

        oyunDurdur.setText("Oyunu Durdur");
        oyunDurdur.addActionListener(this::oyunDurdurActionPerformed);
        jMenu3.add(oyunDurdur);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(anaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(sifreGrsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(sifreKytPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 861, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 43, Short.MAX_VALUE)
                    .addComponent(anaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 44, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(sifreGrsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(sifreKytPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void btnSifreKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSifreKaydetActionPerformed
        String yeniSifre = kaydetTxtField.getText();
        if (!(yeniSifre.equals(""))) {
            try (BufferedWriter bw = new BufferedWriter(new FileWriter("C:\\P2Oyun\\TXTDosyalar\\sifre.txt"))) {
                bw.write(yeniSifre);
                sifre = yeniSifre;
                java.awt.CardLayout cl = (java.awt.CardLayout) this.getContentPane().getLayout();
                cl.show(this.getContentPane(), "GIRIS");
            } catch (IOException e) {
                System.out.println("HATA!! =" + e);
            }
        }
    }//GEN-LAST:event_btnSifreKaydetActionPerformed

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        if (girisTxtField.getText().equals(sifre)) {
            logKaydet(sifre, "BAŞARILI");
            jMenuBar1.setVisible(true);

            java.awt.CardLayout cl = (java.awt.CardLayout) this.getContentPane().getLayout();
            cl.show(this.getContentPane(), "ANAPANEL");
            this.setSize(750, 500);

        } else if (!(sifreBar.getValue() == sifreBar.getMaximum() - 1)) {
            logKaydet(girisTxtField.getText(), "BAŞARISIZ (Hatalı Şifre)");
            sifreBar.setValue(sifreBar.getValue() + 1);
        } else {
            logKaydet(girisTxtField.getText(), "BAŞARISIZ (Haklar tükendi)");
            sifreBar.setValue(sifreBar.getValue() + 1);
            btnGiris.setEnabled(false);
        }
    }//GEN-LAST:event_btnGirisActionPerformed

    private void oyunBaslatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyunBaslatActionPerformed
        gecenSureSaniye = 0;
        lblSure.setText("Süre: 0 sn");

        if (oyunTimer != null && oyunTimer.isRunning()) {
            oyunTimer.stop();
        }
        oyunTimer = new javax.swing.Timer(1000, (java.awt.event.ActionEvent e) -> {
            gecenSureSaniye++;
            lblSure.setText("Süre: " + gecenSureSaniye + " sn");
        });
        oyunTimer.start();
        tahminSayisi = 1;
        setOyunButonlariAktif(true);

        pnlDaragaci.removeAll();
        pnlDaragaci.setLayout(new java.awt.BorderLayout());
        pnlDaragaci.add(daragaciResimEtiketi, java.awt.BorderLayout.CENTER);

        kelimePanel.removeAll();
        kelimePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        kelimeIndex = rnd.nextInt(stringList.size());
        secilenKelime = stringList.get(kelimeIndex).toUpperCase().trim();

        System.out.println("Seçilen Kelime: " + secilenKelime);
        harfEtiketleri = new javax.swing.JLabel[secilenKelime.length()];

        for (int i = 0; i < secilenKelime.length(); i++) {
            harfEtiketleri[i] = new javax.swing.JLabel(" * ");
            harfEtiketleri[i].setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 24));
            harfEtiketleri[i].setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.BLACK));
            kelimePanel.add(harfEtiketleri[i]);
        }
        kelimePanel.revalidate();
        kelimePanel.repaint();
    }//GEN-LAST:event_oyunBaslatActionPerformed

    private void setOyunButonlariAktif(boolean aktif) {
        btnHarfTahmin.setEnabled(aktif);
        btnKelimeTahmin.setEnabled(aktif);
        tahminHarf.setEnabled(aktif);
        tahminKelimetxt.setEnabled(aktif);
    }

    private boolean kelimeTamamenAcildiMi() {
        if (harfEtiketleri == null) {
            return false;
        }
        for (javax.swing.JLabel label : harfEtiketleri) {
            if (label.getText().contains("*")) {
                return false;
            }
        }
        resimGuncelle(271);
        return true;
    }

    private void resimGuncelle(int tahminSayisi) {
        try {
            String resimYolu = "C:\\P2Oyun\\Resimler\\" + tahminSayisi + ".jpg";
            java.io.File dosya = new java.io.File(resimYolu);

            if (dosya.exists()) {

                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(resimYolu);
                java.awt.Image img = icon.getImage();
                java.awt.Image yeniImg = img.getScaledInstance(pnlDaragaci.getWidth(), pnlDaragaci.getHeight(), java.awt.Image.SCALE_SMOOTH);

                daragaciResimEtiketi.setIcon(new javax.swing.ImageIcon(yeniImg));
            } else {
                System.out.println("Resim bulunamadı: " + resimYolu);
                daragaciResimEtiketi.setIcon(null);
            }
            pnlDaragaci.revalidate();
            pnlDaragaci.repaint();
        } catch (Exception e) {
            System.out.println("Resim yükleme hatası: " + e.getMessage());
        }
    }
    private void oyunSifirlaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyunSifirlaActionPerformed
        oyunBaslatActionPerformed(evt);
    }//GEN-LAST:event_oyunSifirlaActionPerformed

    private void oyunDurdurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oyunDurdurActionPerformed
        if (oyunTimer != null) {
            oyunTimer.stop();
        }
        setOyunButonlariAktif(false);
    }//GEN-LAST:event_oyunDurdurActionPerformed

    private void btnHarfTahminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHarfTahminActionPerformed
        bildiMi = false;
        String olasiHarf = tahminHarf.getText().toUpperCase();
        if (olasiHarf.isEmpty()) {
            return;
        }

        char olasiHarfler[] = olasiHarf.toCharArray();

        for (char c : olasiHarfler) {
            for (int i = 0; i < secilenKelime.length(); i++) {
                if (c == secilenKelime.charAt(i)) {
                    harfEtiketleri[i].setText(" " + c + " ");
                    bildiMi = true;
                }
            }
        }
        tahminHarf.setText("");
        if (!(bildiMi)) {
            resimGuncelle(tahminSayisi);
            tahminSayisi++;
        }

        if (kelimeTamamenAcildiMi()) {
            resimGuncelle(271);
            oyunKaydet("GALIBIYET", gecenSureSaniye);
            oyunTimer.stop();
            setOyunButonlariAktif(false);
        } else if (tahminSayisi > 11) {
            oyunKaydet("MAGLUBIYET", gecenSureSaniye);
            oyunTimer.stop();
            setOyunButonlariAktif(false);
        }


    }//GEN-LAST:event_btnHarfTahminActionPerformed

    private void btnKelimeTahminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelimeTahminActionPerformed
        String tahminKelime = tahminKelimetxt.getText().toUpperCase().trim();
        if (tahminKelime.isEmpty()) {
            return;
        }

        if (tahminKelime.equals(secilenKelime)) {
            for (int i = 0; i < secilenKelime.length(); i++) {
                harfEtiketleri[i].setText(" " + secilenKelime.charAt(i) + " ");
            }
            resimGuncelle(271);
            oyunKaydet("GALIBIYET", gecenSureSaniye);
            oyunTimer.stop();
            setOyunButonlariAktif(false);
        } else {
            resimGuncelle(tahminSayisi);
            tahminSayisi++;
        }

        if (tahminSayisi > 11) {
            oyunKaydet("MAGLUBIYET", gecenSureSaniye);
            oyunTimer.stop();
            setOyunButonlariAktif(false);
        }
        tahminKelimetxt.setText("");
    }//GEN-LAST:event_btnKelimeTahminActionPerformed

    private void tabPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabPanelStateChanged
        oyunlariYukle(model1);
        logYukle(model2);
    }//GEN-LAST:event_tabPanelStateChanged

    private void btnTemizleOyunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemizleOyunActionPerformed
        JPasswordField sifreOnay = new JPasswordField();
        int secim = JOptionPane.showConfirmDialog(null,
                sifreOnay,
                "Lütfen şifreyi Giriniz:",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (secim == JOptionPane.OK_OPTION) {
            String girilenSifre = new String(sifreOnay.getPassword());
            String dogruSifre = sifre;

            if (girilenSifre.equals(dogruSifre)) {
                dosyayiTemizle("oyunlar.txt");
                if (model1 != null) {
                    model1.setRowCount(0);
                }
                JOptionPane.showMessageDialog(null, "Tüm oyun geçmişi temizlendi.", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Şifre yanlış.", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTemizleOyunActionPerformed

    private void btnTemizleLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemizleLogActionPerformed
        JPasswordField sifreOnay = new JPasswordField();
        int secim = JOptionPane.showConfirmDialog(null,
                sifreOnay,
                "Lütfen şifreyi Giriniz:",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (secim == JOptionPane.OK_OPTION) {
            String girilenSifre = new String(sifreOnay.getPassword());
            String dogruSifre = sifre;

            if (girilenSifre.equals(dogruSifre)) {
                dosyayiTemizle("log.txt");
                if (model2 != null) {
                    model2.setRowCount(0);
                }
                JOptionPane.showMessageDialog(null, "Tüm oyun geçmişi temizlendi!", "Başarılı", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Şifre Yanlış.", "Hata", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnTemizleLogActionPerformed

    private void dosyayiTemizle(String dosyaAdi) {
        String logDosyasi = "C:\\P2Oyun\\TXTDosyalar\\"+dosyaAdi;
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(logDosyasi, false))) {
            bw.write("");
        } catch (IOException e) {
            System.out.println("Dosya temizlenirken bir hata oluştu: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "Dosya silinirken teknik hata oluştu.", "Hata", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void logKaydet(String kullaniciGirdisi, String durum) {
        String logDosyasi = "C:\\P2Oyun\\TXTDosyalar\\log.txt";
        java.time.format.DateTimeFormatter dtf = java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
        String zaman = java.time.LocalDateTime.now().format(dtf);
        String logSatiri = String.format("[%s] Giriş Denemesi - Girilen: '%s' - Durum: %s%n", zaman, kullaniciGirdisi, durum);
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(logDosyasi, true))) {
            bw.write(logSatiri);
        } catch (IOException e) {
            System.out.println("Log yazılırken hata oluştu: " + e.getMessage());
        }
    }

    private void oyunKaydet(String oyunDurumu, int sureSaniye) {
        String logDosyasi = "C:\\P2Oyun\\TXTDosyalar\\oyunlar.txt";

        String logSatiri = String.format(" Oyun Durumu: %s - Geçen Süre: %d saniye%n",
                oyunDurumu, sureSaniye);

        try (java.io.BufferedWriter bw = new java.io.BufferedWriter(new java.io.FileWriter(logDosyasi, true))) {
            bw.write(logSatiri);
        } catch (java.io.IOException e) {
            System.out.println("Log yazılırken hata oluştu: " + e.getMessage());
        }
    }

    private void logYukle(DefaultTableModel model2) {
        String logDosyasi = "C:\\P2Oyun\\TXTDosyalar\\log.txt";
        model2.setRowCount(0);

        try (BufferedReader br = new BufferedReader(new FileReader(logDosyasi))) {
            String satir;

            while ((satir = br.readLine()) != null) {
                try {
                    String zaman = satir.substring(satir.indexOf("[") + 1, satir.indexOf("]"));

                    int girilenBaslangic = satir.indexOf("Girilen: '") + "Girilen: '".length();
                    int girilenBitis = satir.indexOf("'", girilenBaslangic);
                    String girilenDeger = satir.substring(girilenBaslangic, girilenBitis);

                    int durumBaslangic = satir.indexOf("Durum: ") + "Durum: ".length();
                    String durum = satir.substring(durumBaslangic).trim();

                    model2.addRow(new Object[]{zaman, girilenDeger, durum});

                } catch (Exception e) {
                    System.out.println("Log satırı çözümlenemedi: " + satir);
                }
            }
        } catch (IOException e) {
            System.out.println("Log dosyası okunurken hata oluştu: " + e.getMessage());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new o1().setVisible(true));
    }

    public void oyunlariYukle(DefaultTableModel tableModel) {
        String logDosyasi = "C:\\P2Oyun\\TXTDosyalar\\oyunlar.txt";
        tableModel.setRowCount(0);
        
        try (BufferedReader br = new BufferedReader(new FileReader(logDosyasi))) {
            String satir;
            while ((satir = br.readLine()) != null) {
                try {

                    int durumBaslangic = satir.indexOf("Oyun Durumu: ") + "Oyun Durumu: ".length();
                    int durumBitis = satir.indexOf(" - Geçen Süre:");
                    String oyunDurumu = satir.substring(durumBaslangic, durumBitis).trim();

                    int sureBaslangic = satir.indexOf("Geçen Süre: ") + "Geçen Süre: ".length();
                    int sureBitis = satir.indexOf(" saniye");
                    String sureSaniye = satir.substring(sureBaslangic, sureBitis).trim();

                    tableModel.addRow(new Object[]{oyunDurumu, sureSaniye});

                } catch (Exception e) {
                    System.out.println("Satır ayrıştırılamadı, atlanıyor: " + satir);
                }
            }
        } catch (Exception e) {
            System.out.println("Dosya okunurken hata oluştu: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anaPanel;
    private javax.swing.JButton btnGiris;
    private javax.swing.JButton btnHarfTahmin;
    private javax.swing.JButton btnKelimeTahmin;
    private javax.swing.JButton btnSifreKaydet;
    private javax.swing.JButton btnTemizleLog;
    private javax.swing.JButton btnTemizleOyun;
    private javax.swing.JTextField girisTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kaydetTxtField;
    private javax.swing.JPanel kelimePanel;
    private javax.swing.JLabel lblSure;
    private javax.swing.JPanel logTab;
    private javax.swing.JTable logTablosu;
    private javax.swing.JMenuItem oyunBaslat;
    private javax.swing.JMenuItem oyunDurdur;
    private javax.swing.JMenuItem oyunSifirla;
    private javax.swing.JPanel oyunTab;
    private javax.swing.JPanel pnlDaragaci;
    private javax.swing.JProgressBar sifreBar;
    private javax.swing.JPanel sifreGrsPanel;
    private javax.swing.JPanel sifreKytPanel;
    private javax.swing.JPanel skorTab;
    private javax.swing.JTable skorTablosu;
    private javax.swing.JTabbedPane tabPanel;
    private javax.swing.JTextField tahminHarf;
    private javax.swing.JTextField tahminKelimetxt;
    // End of variables declaration//GEN-END:variables
}
